### ISSUE TITLE
ValueError: Missing access token.

### ISSUE THREAD

**Issue by benvaughan** [praveendath92/fitbit-googlefit#46]
Hi there,

I'm setting this up on a Raspberry Pi. I have successfully authenticated (locally on the pi) on both the Fitbit and Google ends. However, when I try to run the app remotely over SSH I get the following error:

sudo python3 app.py

Traceback (most recent call last):
  File "app.py", line 110, in <module>
    main()
  File "app.py", line 54, in main
    userProfile = remote.ReadFromFitbit(fitbitClient.user_profile_get)
  File "/home/pi/Documents/fitbitenv/fitbit-googlefit/remote.py", line 55, in ReadFromFitbit
    resp = api_call(*args,**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/fitbit/api.py", line 256, in user_profile_get
    return self.make_request(url)
  File "/usr/local/lib/python3.4/dist-packages/fitbit/api.py", line 227, in make_request
    response = self.client.make_request(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/fitbit/api.py", line 68, in make_request
    response = self._request(method, url, data=data, auth=auth, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/fitbit/api.py", line 55, in _request
    return self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 499, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 431, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 307, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 538, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python3.4/dist-packages/requests_oauthlib/oauth2_auth.py", line 35, in __call__
    http_method=r.method, body=r.body, headers=r.headers)
  File "/usr/local/lib/python3.4/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 191, in add_token
    raise ValueError("Missing access token.")
ValueError: Missing access token.

I have also tried running it locally with the same error. The fitbit and google json files are in the auth folder and seem to have the appropriate values in them. Apologies if there is an obvious answer to this but I'm a bit lost here!

Cheers,
Ben

**Comment by lightmaster** [comment]
Make sure you set it up in a virtualenv, and then run it with out sudo.

Also, I've created a fork of this report that automates the setup and everything as much as possible. You still have to copy/paste the URLs on a headless computer, but you don't have to worry about mistyping any commands. Clone it into a different folder and see if it runs fine for you. https://github.com/lightmaster/fitbit-googlefit

**Comment by benvaughan** [comment]
Thanks for the response lightmaster. I did set it up within a virtualenv environment and I did run it without sudo without success.

I have tried your fork however I am getting the following error after I input the fitbit secret:

Traceback (most recent call last):
  File "app.py", line 198, in <module>
    main()
  File "app.py", line 103, in main
    subprocess.run("cd ./auth && ./auth_fitbit.py -i " + fitbitclientid + " -s " + fitbitclientsecret + " --console", shell=True)
AttributeError: 'module' object has no attribute 'run'

The only change I made to your README instructions was in the 'Run App.py' section I cloned your fork rather than the this version as your instructions suggested. I assumed this was a cut/paste error, i.e. you forgot to update the address to your fork. Was I wrong about that?

**Comment by lightmaster** [comment]
Module object has no attribute run means you're probably running python3 version lower than 3.5. gotta find a different command that works nicely that works on a lower version.

My fork is intended to be pulled back into this one once I'm sure it works on all platforms. Need to change that part of the README.md to just say to use the green button at the top though so it works for both.

**Comment by lightmaster** [comment]
Give me a little bit and I'll write that section with a different command that should work on lower versions of Python3.

**Comment by lightmaster** [comment]
Pull the repo again with `git pull` and try running it again. I changed the subprocess.run command to subprocess. call which should work on python3.4 that you're running.

**Comment by benvaughan** [comment]
Thanks again for your help lightmaster, and my apologies for not realising I was running a lower version of python3. I pulled your update and fitbit verfication worked fine. Google verification hit a snag however. I got a verfication code from Google but when I enter it I get the following error:

Enter verification code: ***Verification code from google***
Authentication has failed: invalid_clientThe OAuth client was not found.
Traceback (most recent call last):
  File "app.py", line 198, in <module>
    main()
  File "app.py", line 130, in main
    fitbitClient,googleClient = helper.GetFitbitClient(),helper.GetGoogleClient()
  File "/home/pi/Documents/fitbit-googlefit/helpers.py", line 38, in GetGoogleClient
    http = credentials.authorize(httplib2.Http())
AttributeError: 'NoneType' object has no attribute 'authorize'

Is this another side-effect of me running the wrong python3 version?

**Comment by lightmaster** [comment]
The subprocess.run command was the only part that required 3.5. Since I replaced that with subprocess.call, it should work on 3.4 with no problem.

Make sure there's no white spaces in the client id and secret from Google. Apparently Google's copy button adds a leading and trailing whitespace to both.

**Comment by lightmaster** [comment]
I just pushed a new update that automatically strips out any leading and trailing whitespaces.

**Comment by benvaughan** [comment]
That did it! Working now so it must have been the whitespace issue. Thanks for all your efforts lightmaster, very appreciated!
